# Generated by rust2rpm 10
%bcond_with check
%global debug_package %{nil}

%global crate lexical-core

Name:           rust-%{crate}0.4
Version:        0.4.6
Release:        3%{?dist}
Summary:        Lexical, to- and from-string conversion routines

# Upstream license specification: MIT/Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/lexical-core
Source:         %{crates_source}
# Initial patched metadata
# * Update quickcheck to 0.9, https://github.com/Alexhuszagh/rust-lexical/commit/fefe81850e5678450ec0f001f562b182694caadf
# * Update static_assertions to 1, https://github.com/Alexhuszagh/rust-lexical/pull/31
# * Update arrayvec to 0.5, https://github.com/Alexhuszagh/rust-lexical/pull/32
Patch0:         lexical-core-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Lexical, to- and from-string conversion routines.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md CHANGELOG
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+arrayvec-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+arrayvec-devel %{_description}

This package contains library source intended for building other packages
which use "arrayvec" feature of "%{crate}" crate.

%files       -n %{name}+arrayvec-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+correct-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+correct-devel %{_description}

This package contains library source intended for building other packages
which use "correct" feature of "%{crate}" crate.

%files       -n %{name}+correct-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+dtoa-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dtoa-devel %{_description}

This package contains library source intended for building other packages
which use "dtoa" feature of "%{crate}" crate.

%files       -n %{name}+dtoa-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+grisu3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+grisu3-devel %{_description}

This package contains library source intended for building other packages
which use "grisu3" feature of "%{crate}" crate.

%files       -n %{name}+grisu3-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+radix-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+radix-devel %{_description}

This package contains library source intended for building other packages
which use "radix" feature of "%{crate}" crate.

%files       -n %{name}+radix-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+rounding-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rounding-devel %{_description}

This package contains library source intended for building other packages
which use "rounding" feature of "%{crate}" crate.

%files       -n %{name}+rounding-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+ryu-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ryu-devel %{_description}

This package contains library source intended for building other packages
which use "ryu" feature of "%{crate}" crate.

%files       -n %{name}+ryu-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+table-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+table-devel %{_description}

This package contains library source intended for building other packages
which use "table" feature of "%{crate}" crate.

%files       -n %{name}+table-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+trim_floats-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+trim_floats-devel %{_description}

This package contains library source intended for building other packages
which use "trim_floats" feature of "%{crate}" crate.

%files       -n %{name}+trim_floats-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+unchecked_index-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unchecked_index-devel %{_description}

This package contains library source intended for building other packages
which use "unchecked_index" feature of "%{crate}" crate.

%files       -n %{name}+unchecked_index-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
# Port to the static_assertions to 1.x
sed -e '/const_assert!/s/([^;)]\+;\s*/(/' -i src/util/table.rs src/atof/algorithm/small_powers.rs
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.4.6-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Fri Dec 06 20:37:57 CET 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0.4.6-2
- Update arrayvec to 0.5

* Tue Nov 26 17:13:25 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.4.6-1
- Initial package
